site_name: MOLGENIS Armadillo Docs
site_url: https://molgenis.github.io/molgenis-service-armadillo/
repo_name: MOLGENIS Armadillo
repo_url: https://github.com/molgenis/molgenis-service-armadillo
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: img/favicon.ico
  logo: img/armadillo-logo.png
  features:
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.footer
extra_css:
  - css/simple.css
copyright: When using MOLGENIS Armadillo, don't forget to cite us https://doi.org/10.1093/bioinformatics/btae726
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/molgenis
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/molgenis
nav:
  - "Basic Concepts": pages/basic_concepts.md
  - "Quick Start" : pages/quick_start.md
  - "About us": pages/about_us.md
  - Basic Usage:
      - pages/basic_usage/index.md
      - "Armadillo User Interface": pages/basic_usage/armadillo_ui.md
      - "Central Analysis Server (CAS)": pages/basic_usage/central_analysis_server.md
      - "DSMolgenisArmadillo": pages/basic_usage/ds_molgenis_armadillo.md
      - "MolgenisArmadillo": pages/basic_usage/molgenis_armadillo.md
      - "dsUpload & dsDictionaries": pages/basic_usage/dsupload_dsdictionaries.md
      - "dsLite": pages/basic_usage/dslite.md
      - "Authentication Server": pages/basic_usage/auth.md
#  - "Example Usage": pages/examples_usage.md
#  - "Advanced Usage": pages/advanced_usage.md
  - Install, Setup and Management:
      - pages/install_management/index.md
      - "Armadillo Installation": pages/install_management/armadillo_install.md
      - "Armadillo Management": pages/install_management/armadillo_management.md
      - "Armadillo Minor Release Update": pages/install_management/armadillo_minor_release_update.md
      - "Migrate Armadillo 2 to 3": pages/install_management/armadillo_migrate_2_to_3.md
      - "Migrate Armadillo 3 to 4": pages/install_management/armadillo_migrate_3_to_4.md
  - "Developer guides": pages/dev_guides.md
  - "License": pages/license.md
  - "FAQ": pages/faq.md
#  - "Troubleshooting": pages/troubleshooting.md
  - "Contact": pages/contact.md
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.keys
