###
POST {{host}}/logout

### authenticate with basic auth
GET {{host}}/profiles
Authorization: Basic admin admin

###
POST {{host}}/select-profile

default

###
POST {{host}}/select-profile

exposome

###
GET {{host}}/packages

