POST {{host}}/logout

###
GET {{host}}/packages
Authorization: Basic admin admin

###
GET {{host}}/resources
Authorization: Basic admin admin

###
HEAD {{host}}/resources/local/project/patient

###
POST {{host}}/load-resource?symbol=patientResource&resource=local/project/patient

###
POST {{host}}/symbols/patient
Content-Type: text/plain

dataFrameDS("patientResource")

###
GET {{host}}/symbols

###
POST {{host}}/execute
Accept: application/octet-stream
Content-Type: text/plain

meanDS("patientResource")

###
DELETE {{host}}/symbols/D

###
GET {{host}}/lastcommand
accept: application/json

###
GET {{host}}/lastresult
accept: application/octet-stream

###