###
POST {{host}}/logout

###
GET {{host}}/symbols
Authorization: Basic admin admin

###
POST {{host}}/symbols/D
Content-Type: text/plain

1:5

###
GET {{host}}/symbols

###
DELETE {{host}}/symbols/D

### List user workspaces
GET {{host}}/workspaces

### Create a user workspace
POST {{host}}/workspaces/test

### Load a user workspace
POST {{host}}/load-workspace?id=test

### Delete a user workspace
DELETE {{host}}/workspaces/test