### get info
GET {{host}}/actuator/info

### retrieve R processes
GET {{host}}/actuator/rserveProcesses
Authorization: Basic admin admin

### delete process by pid
DELETE {{host}}/actuator/rserveProcesses?pid=157
Authorization: Basic admin admin

### get current r processes by environment
GET {{host}}/actuator/metrics/rserve.processes.current?tag=environment:default
Accept: application/vnd.spring-boot.actuator.v3+json
Authorization: Basic admin admin