###
POST {{host}}/logout

### authenticate with basic auth
GET {{host}}/containers
Authorization: Basic admin admin

###
POST {{host}}/select-container

default

###
POST {{host}}/select-container

exposome

###
GET {{host}}/packages

