GET {{host}}/tables
Authorization: Basic admin admin

###
# Async and sync assign, parse exception => BAD REQUEST
# No command created, message in the json
POST {{host}}/symbols/D
Content-Type: text/plain

colnames(D

###
# Async and sync execute, parse exception => BAD REQUEST
# No command created, message in the json *if you accept it*
POST {{host}}/execute
Accept: application/octet-stream,application/json
Content-Type: text/plain

colnames(D

###
# Synchronous execute, R error => 500
# Empty response, message in /lastcommand
POST {{host}}/execute
Accept: application/octet-stream,application/json
Content-Type: text/plain

X

###
GET {{host}}/lastcommand

###
# Synchronous assign, R error => 500
# Empty response, message in /lastcommand
POST {{host}}/symbols/D
Content-Type: text/plain

X

###
GET {{host}}/lastcommand

###
# async assign, R exception => 201 with Location header because we don't know that anything is wrong yet
POST {{host}}/symbols/D?async=true
Content-Type: text/plain

X
### But in the lastcommand status FAILED and message
GET {{host}}/lastcommand

### The lastresult returns NOT_FOUND if command failed
GET {{host}}/lastresult

### Invalid package file BAD_REQUEST
POST {{host}}/install-package
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="input.txt"

// The 'invalid_rpackage.txt' file will be uploaded
< ./invalid_rpackage.txt
