####################### data upload ######################
# First upload the data into the minio                   #
# In the folder docker/test/data you can test data       #
# Navigate to http://localhost:9000                      #
# Login with molgenis:molgenis                           #
# Create a bucket called shared-lifecycle                #
# Upload the folders in docker/test/data to the bucket   #
##########################################################

###
POST {{host}}/logout

###
GET {{host}}/v3/api-docs

### authenticate with JWT token
GET {{host}}/tables
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlcwbmltejhpYU9DLW16OXNaTVRiVzRfbFdMMCJ9.eyJhdWQiOiJiMzk2MjMzYi1jZGIyLTQ0OWUtYWM1Yy1hMGQyOGIzOGY3OTEiLCJleHAiOjE1OTMxMDEwNTAsImlhdCI6MTU5MzA5NzQ1MCwiaXNzIjoiaHR0cHM6Ly9hdXRoLm1vbGdlbmlzLm9yZyIsInN1YiI6ImNjY2RlMmZlLTc0NWEtNDUxMS05Yjk1LTNlZTgzNDYxOTNiNiIsImF1dGhlbnRpY2F0aW9uVHlwZSI6IlBBU1NXT1JEIiwiZW1haWwiOiJmLmtlbHBpbkB1bWNnLm5sIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJJYVpGajZWRGl0TWpTcmxhbTlWZGJBIiwiY19oYXNoIjoidHdxWS1kMl9IOG5leWNjQmVmMFE5USIsImFwcGxpY2F0aW9uSWQiOiJiMzk2MjMzYi1jZGIyLTQ0OWUtYWM1Yy1hMGQyOGIzOGY3OTEiLCJyb2xlcyI6WyJTVSJdLCJwb2xpY3kiOiJyZWFkd3JpdGUifQ.mEZfqpBfNnaLKZw0tn0VJwGlx3TKqtGKX4TqeeMg0wvwetVrTfk_7nCc2a1BgnrhHQzFncUc5uM67B95yVsZuxpJ-T2uBKGp2k890n5D2i5o0hM6kvfv3OJHHHNyF_MuDHS0ST3bVBuUo8Sc1nbvUVJtSqQZ51HXaXbwKH_fbRxvBpuHMWSGXZdzHNdHELvaBFHPV_aMHpN6jyK1AY5oc-vXVIOsLOy6-i2tK1Hjnm6iI8O6CD1f4IF7H_mp_x3Dfbk30nvR4RchgPq26ekPpYm7P96L_RZTwh4FLxbjN43AdOgmiLjL_RMkGL3spsnQX-nkzwvkvuL-PmSjsB7jcw

### authenticate with basic auth
GET {{host}}/tables
Authorization: Basic admin admin

###
HEAD {{host}}/tables/lifecycle/core/nonrep

###
POST {{host}}/load-table?symbol=D&table=lifecycle/core/nonrep

###
POST {{host}}/load-table?symbol=D&table=lifecycle/core/nonrep&variables=agebirth_m_d

###
GET {{host}}/symbols

###
POST {{host}}/execute
Accept: application/octet-stream
Content-Type: text/plain

meanDS(D$agebirth_m_d)

###
DELETE {{host}}/symbols/D

###
GET {{host}}/methods/aggregate

###
GET {{host}}/methods/assign

###
POST {{host}}/symbols/D?async=true
Content-Type: text/plain

0:5

###
POST {{host}}/execute?async=true
Accept: application/octet-stream
Content-Type: text/plain

meanDS(D)

###
GET {{host}}/lastcommand
accept: application/json

###
GET {{host}}/lastresult
accept: application/octet-stream

###
GET {{host}}/whitelist

###
POST {{host}}/whitelist/DSI