---
galaxy_info:
  role_name: armadillo
  author: Sido Haakma
  description: Armadillo service that handles requests from the DataSHIELD client and secures the data to be non-disclosive
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
  - name: CentOS
    versions:
    - 7
    - 8

  galaxy_tags: [federation]

dependencies: []