version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:9.0.2
    ports:
      - "5010:5010"
      - "9600:9600"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    volumes:
      - ${PWD}/logs/audit.log:/usr/share/filebeat/input/audit.log
      - ${PWD}/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - filebeat
