GET http://localhost:8080/authentication
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZGZGxjSWJNQ3h4SjVQTFBWWmFTLXMyX3lwTSJ9.eyJhdWQiOiJmYmEwZGIzOC1lOTJhLTRlOWQtOWVhZC1jNzBlZWIwMGE3NTIiLCJleHAiOjE1ODQ2OTQ4MjksImlhdCI6MTU4NDY5MTIyOSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo5MDExIiwic3ViIjoiYTIxNjA1ZDItNzQxYS00ZTFjLWJiNmEtMTRiZjdjMjNjM2U2IiwiYXV0aGVudGljYXRpb25UeXBlIjoiUEFTU1dPUkQiLCJlbWFpbCI6ImZsZXVyQGtlbHBpbi5ubCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiU2lRbG5leWFVNXpwVFE1Vkd3eVg4USIsImNfaGFzaCI6ImRDRVAwZU9sWUdTZ3Jyd3htZ0UzSXciLCJhcHBsaWNhdGlvbklkIjoiZmJhMGRiMzgtZTkyYS00ZTlkLTllYWQtYzcwZWViMDBhNzUyIiwicm9sZXMiOlsiR0VDS09fQURNSU4iLCJNT0xHRU5JU19ERVYiXX0.h4wephdqoXXRcySogNYqara8mP7CYnNOjGm-2RWQo3XNE8M4NDC4_E2R4p9cl4EvtvGoB4vVPhVMVvsljS5jREb-qmE-tlYzrJsGOK5hkU5WkwF7ob5L9zbcoR9bI92jmgXhN5Ja1--x0xlnFtUfQm_jGQ4v7sUgyGGRXyr9K_d3mDjWKgVNaySX8bev_OG92X1jFUsySlG3AQs8Su7MEe5VYxRpXEBbKxz3I_AuGLViC27H2OICS7S098ZZihGMHn_QG9gJzMhkkxKrrgohAolwwQx1qahPNHvswYIzWbHIUlgyCPxWz7GmyCu2kgkCLzjDEOwZTKo1nHsowrAM4w
Accept: application/json
###
