{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: {{ include "armadillo.fullname" . }}
 labels:
   {{- include "armadillo.labels" . | nindent 4 }}  
spec:
 storageClassName: {{ .Values.persistence.storageClass }}
 accessModes:
   - {{ .Values.persistence.accessMode | quote }}
 resources:
   requests:
     storage: {{ .Values.persistence.size | quote }}
 {{- end }}
 
