---
galaxy_info:
  role_name: minio
  author: Sido Haakma
  description: Minio file storage, used to get data into the federated platform
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
  - name: CentOS
    versions:
    - 7
    - 8

  galaxy_tags: [federation]

dependencies: []