/*
 * Metadata API
 * RESTful API to create/read/update/delete metadata.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AttributeData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-14T15:06:09.233Z[GMT]")
public class AttributeData {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("sequenceNr")
  private Integer sequenceNr = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    BOOL("bool"),
    CATEGORICAL("categorical"),
    CATEGORICAL_MREF("categorical_mref"),
    COMPOUND("compound"),
    DATE("date"),
    DATE_TIME("date_time"),
    DECIMAL("decimal"),
    EMAIL("email"),
    ENUM("enum"),
    FILE("file"),
    HTML("html"),
    HYPERLINK("hyperlink"),
    INT("int"),
    LONG("long"),
    MREF("mref"),
    ONE_TO_MANY("one_to_many"),
    SCRIPT("script"),
    STRING("string"),
    TEXT("text"),
    XREF("xref");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("mappedBy")
  private Attribute mappedBy = null;

  @SerializedName("orderBy")
  private List<List> orderBy = null;

  @SerializedName("idAttribute")
  private Boolean idAttribute = null;

  @SerializedName("labelAttribute")
  private Boolean labelAttribute = null;

  @SerializedName("lookupAttributeIndex")
  private Integer lookupAttributeIndex = null;

  @SerializedName("refEntityType")
  private Links refEntityType = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("description_i18n")
  private I18nValue descriptionI18n = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("label_i18n")
  private I18nValue labelI18n = null;

  @SerializedName("nullable")
  private Boolean nullable = null;

  @SerializedName("auto")
  private Boolean auto = null;

  @SerializedName("visible")
  private Boolean visible = null;

  @SerializedName("unique")
  private Boolean unique = null;

  @SerializedName("readOnly")
  private Boolean readOnly = null;

  @SerializedName("aggregatable")
  private Boolean aggregatable = null;

  @SerializedName("enumOptions")
  private List<String> enumOptions = null;

  @SerializedName("categoricalOptions")
  private List<CategoricalOption> categoricalOptions = null;

  @SerializedName("defaultValue")
  private String defaultValue = null;

  @SerializedName("cascadeDelete")
  private Boolean cascadeDelete = null;

  @SerializedName("parentAttribute")
  private Attribute parentAttribute = null;

  @SerializedName("expression")
  private String expression = null;

  @SerializedName("nullableExpression")
  private String nullableExpression = null;

  @SerializedName("visibleExpression")
  private String visibleExpression = null;

  @SerializedName("validationExpression")
  private String validationExpression = null;

  public AttributeData id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AttributeData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AttributeData sequenceNr(Integer sequenceNr) {
    this.sequenceNr = sequenceNr;
    return this;
  }

   /**
   * Get sequenceNr
   * @return sequenceNr
  **/
  @Schema(description = "")
  public Integer getSequenceNr() {
    return sequenceNr;
  }

  public void setSequenceNr(Integer sequenceNr) {
    this.sequenceNr = sequenceNr;
  }

  public AttributeData type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public AttributeData mappedBy(Attribute mappedBy) {
    this.mappedBy = mappedBy;
    return this;
  }

   /**
   * Get mappedBy
   * @return mappedBy
  **/
  @Schema(description = "")
  public Attribute getMappedBy() {
    return mappedBy;
  }

  public void setMappedBy(Attribute mappedBy) {
    this.mappedBy = mappedBy;
  }

  public AttributeData orderBy(List<List> orderBy) {
    this.orderBy = orderBy;
    return this;
  }

  public AttributeData addOrderByItem(List orderByItem) {
    if (this.orderBy == null) {
      this.orderBy = new ArrayList<List>();
    }
    this.orderBy.add(orderByItem);
    return this;
  }

   /**
   * Get orderBy
   * @return orderBy
  **/
  @Schema(description = "")
  public List<List> getOrderBy() {
    return orderBy;
  }

  public void setOrderBy(List<List> orderBy) {
    this.orderBy = orderBy;
  }

  public AttributeData idAttribute(Boolean idAttribute) {
    this.idAttribute = idAttribute;
    return this;
  }

   /**
   * Get idAttribute
   * @return idAttribute
  **/
  @Schema(description = "")
  public Boolean isIdAttribute() {
    return idAttribute;
  }

  public void setIdAttribute(Boolean idAttribute) {
    this.idAttribute = idAttribute;
  }

  public AttributeData labelAttribute(Boolean labelAttribute) {
    this.labelAttribute = labelAttribute;
    return this;
  }

   /**
   * Get labelAttribute
   * @return labelAttribute
  **/
  @Schema(description = "")
  public Boolean isLabelAttribute() {
    return labelAttribute;
  }

  public void setLabelAttribute(Boolean labelAttribute) {
    this.labelAttribute = labelAttribute;
  }

  public AttributeData lookupAttributeIndex(Integer lookupAttributeIndex) {
    this.lookupAttributeIndex = lookupAttributeIndex;
    return this;
  }

   /**
   * Get lookupAttributeIndex
   * @return lookupAttributeIndex
  **/
  @Schema(description = "")
  public Integer getLookupAttributeIndex() {
    return lookupAttributeIndex;
  }

  public void setLookupAttributeIndex(Integer lookupAttributeIndex) {
    this.lookupAttributeIndex = lookupAttributeIndex;
  }

  public AttributeData refEntityType(Links refEntityType) {
    this.refEntityType = refEntityType;
    return this;
  }

   /**
   * Get refEntityType
   * @return refEntityType
  **/
  @Schema(description = "")
  public Links getRefEntityType() {
    return refEntityType;
  }

  public void setRefEntityType(Links refEntityType) {
    this.refEntityType = refEntityType;
  }

  public AttributeData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AttributeData descriptionI18n(I18nValue descriptionI18n) {
    this.descriptionI18n = descriptionI18n;
    return this;
  }

   /**
   * Get descriptionI18n
   * @return descriptionI18n
  **/
  @Schema(description = "")
  public I18nValue getDescriptionI18n() {
    return descriptionI18n;
  }

  public void setDescriptionI18n(I18nValue descriptionI18n) {
    this.descriptionI18n = descriptionI18n;
  }

  public AttributeData label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public AttributeData labelI18n(I18nValue labelI18n) {
    this.labelI18n = labelI18n;
    return this;
  }

   /**
   * Get labelI18n
   * @return labelI18n
  **/
  @Schema(description = "")
  public I18nValue getLabelI18n() {
    return labelI18n;
  }

  public void setLabelI18n(I18nValue labelI18n) {
    this.labelI18n = labelI18n;
  }

  public AttributeData nullable(Boolean nullable) {
    this.nullable = nullable;
    return this;
  }

   /**
   * Get nullable
   * @return nullable
  **/
  @Schema(description = "")
  public Boolean isNullable() {
    return nullable;
  }

  public void setNullable(Boolean nullable) {
    this.nullable = nullable;
  }

  public AttributeData auto(Boolean auto) {
    this.auto = auto;
    return this;
  }

   /**
   * Get auto
   * @return auto
  **/
  @Schema(description = "")
  public Boolean isAuto() {
    return auto;
  }

  public void setAuto(Boolean auto) {
    this.auto = auto;
  }

  public AttributeData visible(Boolean visible) {
    this.visible = visible;
    return this;
  }

   /**
   * Get visible
   * @return visible
  **/
  @Schema(description = "")
  public Boolean isVisible() {
    return visible;
  }

  public void setVisible(Boolean visible) {
    this.visible = visible;
  }

  public AttributeData unique(Boolean unique) {
    this.unique = unique;
    return this;
  }

   /**
   * Get unique
   * @return unique
  **/
  @Schema(description = "")
  public Boolean isUnique() {
    return unique;
  }

  public void setUnique(Boolean unique) {
    this.unique = unique;
  }

  public AttributeData readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @Schema(description = "")
  public Boolean isReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public AttributeData aggregatable(Boolean aggregatable) {
    this.aggregatable = aggregatable;
    return this;
  }

   /**
   * Get aggregatable
   * @return aggregatable
  **/
  @Schema(description = "")
  public Boolean isAggregatable() {
    return aggregatable;
  }

  public void setAggregatable(Boolean aggregatable) {
    this.aggregatable = aggregatable;
  }

  public AttributeData enumOptions(List<String> enumOptions) {
    this.enumOptions = enumOptions;
    return this;
  }

  public AttributeData addEnumOptionsItem(String enumOptionsItem) {
    if (this.enumOptions == null) {
      this.enumOptions = new ArrayList<String>();
    }
    this.enumOptions.add(enumOptionsItem);
    return this;
  }

   /**
   * Get enumOptions
   * @return enumOptions
  **/
  @Schema(description = "")
  public List<String> getEnumOptions() {
    return enumOptions;
  }

  public void setEnumOptions(List<String> enumOptions) {
    this.enumOptions = enumOptions;
  }

  public AttributeData categoricalOptions(List<CategoricalOption> categoricalOptions) {
    this.categoricalOptions = categoricalOptions;
    return this;
  }

  public AttributeData addCategoricalOptionsItem(CategoricalOption categoricalOptionsItem) {
    if (this.categoricalOptions == null) {
      this.categoricalOptions = new ArrayList<CategoricalOption>();
    }
    this.categoricalOptions.add(categoricalOptionsItem);
    return this;
  }

   /**
   * Get categoricalOptions
   * @return categoricalOptions
  **/
  @Schema(description = "")
  public List<CategoricalOption> getCategoricalOptions() {
    return categoricalOptions;
  }

  public void setCategoricalOptions(List<CategoricalOption> categoricalOptions) {
    this.categoricalOptions = categoricalOptions;
  }

  public AttributeData defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @Schema(description = "")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public AttributeData cascadeDelete(Boolean cascadeDelete) {
    this.cascadeDelete = cascadeDelete;
    return this;
  }

   /**
   * Get cascadeDelete
   * @return cascadeDelete
  **/
  @Schema(description = "")
  public Boolean isCascadeDelete() {
    return cascadeDelete;
  }

  public void setCascadeDelete(Boolean cascadeDelete) {
    this.cascadeDelete = cascadeDelete;
  }

  public AttributeData parentAttribute(Attribute parentAttribute) {
    this.parentAttribute = parentAttribute;
    return this;
  }

   /**
   * Get parentAttribute
   * @return parentAttribute
  **/
  @Schema(description = "")
  public Attribute getParentAttribute() {
    return parentAttribute;
  }

  public void setParentAttribute(Attribute parentAttribute) {
    this.parentAttribute = parentAttribute;
  }

  public AttributeData expression(String expression) {
    this.expression = expression;
    return this;
  }

   /**
   * Get expression
   * @return expression
  **/
  @Schema(description = "")
  public String getExpression() {
    return expression;
  }

  public void setExpression(String expression) {
    this.expression = expression;
  }

  public AttributeData nullableExpression(String nullableExpression) {
    this.nullableExpression = nullableExpression;
    return this;
  }

   /**
   * Get nullableExpression
   * @return nullableExpression
  **/
  @Schema(description = "")
  public String getNullableExpression() {
    return nullableExpression;
  }

  public void setNullableExpression(String nullableExpression) {
    this.nullableExpression = nullableExpression;
  }

  public AttributeData visibleExpression(String visibleExpression) {
    this.visibleExpression = visibleExpression;
    return this;
  }

   /**
   * Get visibleExpression
   * @return visibleExpression
  **/
  @Schema(description = "")
  public String getVisibleExpression() {
    return visibleExpression;
  }

  public void setVisibleExpression(String visibleExpression) {
    this.visibleExpression = visibleExpression;
  }

  public AttributeData validationExpression(String validationExpression) {
    this.validationExpression = validationExpression;
    return this;
  }

   /**
   * Get validationExpression
   * @return validationExpression
  **/
  @Schema(description = "")
  public String getValidationExpression() {
    return validationExpression;
  }

  public void setValidationExpression(String validationExpression) {
    this.validationExpression = validationExpression;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeData attributeData = (AttributeData) o;
    return Objects.equals(this.id, attributeData.id) &&
        Objects.equals(this.name, attributeData.name) &&
        Objects.equals(this.sequenceNr, attributeData.sequenceNr) &&
        Objects.equals(this.type, attributeData.type) &&
        Objects.equals(this.mappedBy, attributeData.mappedBy) &&
        Objects.equals(this.orderBy, attributeData.orderBy) &&
        Objects.equals(this.idAttribute, attributeData.idAttribute) &&
        Objects.equals(this.labelAttribute, attributeData.labelAttribute) &&
        Objects.equals(this.lookupAttributeIndex, attributeData.lookupAttributeIndex) &&
        Objects.equals(this.refEntityType, attributeData.refEntityType) &&
        Objects.equals(this.description, attributeData.description) &&
        Objects.equals(this.descriptionI18n, attributeData.descriptionI18n) &&
        Objects.equals(this.label, attributeData.label) &&
        Objects.equals(this.labelI18n, attributeData.labelI18n) &&
        Objects.equals(this.nullable, attributeData.nullable) &&
        Objects.equals(this.auto, attributeData.auto) &&
        Objects.equals(this.visible, attributeData.visible) &&
        Objects.equals(this.unique, attributeData.unique) &&
        Objects.equals(this.readOnly, attributeData.readOnly) &&
        Objects.equals(this.aggregatable, attributeData.aggregatable) &&
        Objects.equals(this.enumOptions, attributeData.enumOptions) &&
        Objects.equals(this.categoricalOptions, attributeData.categoricalOptions) &&
        Objects.equals(this.defaultValue, attributeData.defaultValue) &&
        Objects.equals(this.cascadeDelete, attributeData.cascadeDelete) &&
        Objects.equals(this.parentAttribute, attributeData.parentAttribute) &&
        Objects.equals(this.expression, attributeData.expression) &&
        Objects.equals(this.nullableExpression, attributeData.nullableExpression) &&
        Objects.equals(this.visibleExpression, attributeData.visibleExpression) &&
        Objects.equals(this.validationExpression, attributeData.validationExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, sequenceNr, type, mappedBy, orderBy, idAttribute, labelAttribute, lookupAttributeIndex, refEntityType, description, descriptionI18n, label, labelI18n, nullable, auto, visible, unique, readOnly, aggregatable, enumOptions, categoricalOptions, defaultValue, cascadeDelete, parentAttribute, expression, nullableExpression, visibleExpression, validationExpression);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeData {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sequenceNr: ").append(toIndentedString(sequenceNr)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    mappedBy: ").append(toIndentedString(mappedBy)).append("\n");
    sb.append("    orderBy: ").append(toIndentedString(orderBy)).append("\n");
    sb.append("    idAttribute: ").append(toIndentedString(idAttribute)).append("\n");
    sb.append("    labelAttribute: ").append(toIndentedString(labelAttribute)).append("\n");
    sb.append("    lookupAttributeIndex: ").append(toIndentedString(lookupAttributeIndex)).append("\n");
    sb.append("    refEntityType: ").append(toIndentedString(refEntityType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    descriptionI18n: ").append(toIndentedString(descriptionI18n)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    labelI18n: ").append(toIndentedString(labelI18n)).append("\n");
    sb.append("    nullable: ").append(toIndentedString(nullable)).append("\n");
    sb.append("    auto: ").append(toIndentedString(auto)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    unique: ").append(toIndentedString(unique)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    aggregatable: ").append(toIndentedString(aggregatable)).append("\n");
    sb.append("    enumOptions: ").append(toIndentedString(enumOptions)).append("\n");
    sb.append("    categoricalOptions: ").append(toIndentedString(categoricalOptions)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    cascadeDelete: ").append(toIndentedString(cascadeDelete)).append("\n");
    sb.append("    parentAttribute: ").append(toIndentedString(parentAttribute)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    nullableExpression: ").append(toIndentedString(nullableExpression)).append("\n");
    sb.append("    visibleExpression: ").append(toIndentedString(visibleExpression)).append("\n");
    sb.append("    validationExpression: ").append(toIndentedString(validationExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
