/*
 * Metadata API
 * RESTful API to create/read/update/delete metadata.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EntityTypePatch
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-14T15:06:09.233Z[GMT]")
public class EntityTypePatch {
  @SerializedName("package")
  private String _package = null;

  @SerializedName("label")
  private I18nValue label = null;

  @SerializedName("description")
  private I18nValue description = null;

  @SerializedName("extends")
  private String _extends = null;

  @SerializedName("attributes")
  private List<AttributeCreate> attributes = null;

  public EntityTypePatch _package(String _package) {
    this._package = _package;
    return this;
  }

   /**
   * Get _package
   * @return _package
  **/
  @Schema(description = "")
  public String getPackage() {
    return _package;
  }

  public void setPackage(String _package) {
    this._package = _package;
  }

  public EntityTypePatch label(I18nValue label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public I18nValue getLabel() {
    return label;
  }

  public void setLabel(I18nValue label) {
    this.label = label;
  }

  public EntityTypePatch description(I18nValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public I18nValue getDescription() {
    return description;
  }

  public void setDescription(I18nValue description) {
    this.description = description;
  }

  public EntityTypePatch _extends(String _extends) {
    this._extends = _extends;
    return this;
  }

   /**
   * Get _extends
   * @return _extends
  **/
  @Schema(description = "")
  public String getExtends() {
    return _extends;
  }

  public void setExtends(String _extends) {
    this._extends = _extends;
  }

  public EntityTypePatch attributes(List<AttributeCreate> attributes) {
    this.attributes = attributes;
    return this;
  }

  public EntityTypePatch addAttributesItem(AttributeCreate attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<AttributeCreate>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public List<AttributeCreate> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AttributeCreate> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityTypePatch entityTypePatch = (EntityTypePatch) o;
    return Objects.equals(this._package, entityTypePatch._package) &&
        Objects.equals(this.label, entityTypePatch.label) &&
        Objects.equals(this.description, entityTypePatch.description) &&
        Objects.equals(this._extends, entityTypePatch._extends) &&
        Objects.equals(this.attributes, entityTypePatch.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_package, label, description, _extends, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTypePatch {\n");

    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    _extends: ").append(toIndentedString(_extends)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
