/*
 * Metadata API
 * RESTful API to create/read/update/delete metadata.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EntityTypeCollection
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-14T15:06:09.233Z[GMT]")
public class EntityTypeCollection {
  @SerializedName("links")
  private Links links = null;

  @SerializedName("items")
  private List<EntityType> items = null;

  @SerializedName("page")
  private Page page = null;

  public EntityTypeCollection links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }

  public EntityTypeCollection items(List<EntityType> items) {
    this.items = items;
    return this;
  }

  public EntityTypeCollection addItemsItem(EntityType itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<EntityType>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @Schema(description = "")
  public List<EntityType> getItems() {
    return items;
  }

  public void setItems(List<EntityType> items) {
    this.items = items;
  }

  public EntityTypeCollection page(Page page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @Schema(description = "")
  public Page getPage() {
    return page;
  }

  public void setPage(Page page) {
    this.page = page;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityTypeCollection entityTypeCollection = (EntityTypeCollection) o;
    return Objects.equals(this.links, entityTypeCollection.links) &&
        Objects.equals(this.items, entityTypeCollection.items) &&
        Objects.equals(this.page, entityTypeCollection.page);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, items, page);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTypeCollection {\n");

    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
