/*
 * Metadata API
 * RESTful API to create/read/update/delete metadata.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EntityTypeCreate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-14T15:06:09.233Z[GMT]")
public class EntityTypeCreate {
  @SerializedName("id")
  private String id = null;

  @SerializedName("package")
  private String _package = null;

  @SerializedName("label")
  private I18nValue label = null;

  @SerializedName("description")
  private I18nValue description = null;

  @SerializedName("abstract")
  private String _abstract = null;

  @SerializedName("extends")
  private String _extends = null;

  @SerializedName("attributes")
  private List<AttributeCreate> attributes = new ArrayList<AttributeCreate>();

  public EntityTypeCreate id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public EntityTypeCreate _package(String _package) {
    this._package = _package;
    return this;
  }

   /**
   * Get _package
   * @return _package
  **/
  @Schema(description = "")
  public String getPackage() {
    return _package;
  }

  public void setPackage(String _package) {
    this._package = _package;
  }

  public EntityTypeCreate label(I18nValue label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public I18nValue getLabel() {
    return label;
  }

  public void setLabel(I18nValue label) {
    this.label = label;
  }

  public EntityTypeCreate description(I18nValue description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public I18nValue getDescription() {
    return description;
  }

  public void setDescription(I18nValue description) {
    this.description = description;
  }

  public EntityTypeCreate _abstract(String _abstract) {
    this._abstract = _abstract;
    return this;
  }

   /**
   * Get _abstract
   * @return _abstract
  **/
  @Schema(description = "")
  public String getAbstract() {
    return _abstract;
  }

  public void setAbstract(String _abstract) {
    this._abstract = _abstract;
  }

  public EntityTypeCreate _extends(String _extends) {
    this._extends = _extends;
    return this;
  }

   /**
   * Get _extends
   * @return _extends
  **/
  @Schema(description = "")
  public String getExtends() {
    return _extends;
  }

  public void setExtends(String _extends) {
    this._extends = _extends;
  }

  public EntityTypeCreate attributes(List<AttributeCreate> attributes) {
    this.attributes = attributes;
    return this;
  }

  public EntityTypeCreate addAttributesItem(AttributeCreate attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(required = true, description = "")
  public List<AttributeCreate> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AttributeCreate> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityTypeCreate entityTypeCreate = (EntityTypeCreate) o;
    return Objects.equals(this.id, entityTypeCreate.id) &&
        Objects.equals(this._package, entityTypeCreate._package) &&
        Objects.equals(this.label, entityTypeCreate.label) &&
        Objects.equals(this.description, entityTypeCreate.description) &&
        Objects.equals(this._abstract, entityTypeCreate._abstract) &&
        Objects.equals(this._extends, entityTypeCreate._extends) &&
        Objects.equals(this.attributes, entityTypeCreate.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _package, label, description, _abstract, _extends, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTypeCreate {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _package: ").append(toIndentedString(_package)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    _abstract: ").append(toIndentedString(_abstract)).append("\n");
    sb.append("    _extends: ").append(toIndentedString(_extends)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
