plugins {
    id "base"
    id "com.github.node-gradle.node" version "7.0.2"
}

def nodeSpec = {
    version = '24.18.1'
    npmVersion = '11.16.0'
    download = true
}

node {
    with nodeSpec
}

tasks.register('installCorepack', NpmTask) {
    args = ['install', '--global', 'corepack']
}

tasks.register('corepackEnable', NpmTask) {
    dependsOn installCorepack
    args = ['exec', '--yes', '--', 'corepack', 'enable']
}

tasks.register('yarnInstall', NpmTask) {
    dependsOn corepackEnable
    args = ['exec', '--yes', '--', 'corepack', 'yarn', 'install', '--immutable']
}

tasks.register('format', NpmTask) {
    dependsOn yarnInstall
    args = ['exec', '--', 'corepack', 'yarn', 'run', 'format']
    inputs.files(fileTree('src'))
    outputs.dir('src')
}

tasks.register('mybuild', NpmTask) {
    dependsOn yarnInstall
    args = ['exec', '--', 'corepack', 'yarn', 'run', 'build']
    inputs.file('package.json')
    inputs.files(fileTree('src'))
    inputs.files(fileTree('public'))
    inputs.file('vite.config.js')
    inputs.file('tsconfig.json')
    inputs.file('shims-vue.d.ts')
    inputs.file('jest.config.cjs')
    inputs.file('tsconfig.node.json')
    inputs.file('index.html')
    outputs.dir('dist')
    outputs.cacheIf { false }
}

tasks.register('test', NpmTask) {
    dependsOn mybuild
    args = ['exec', '--', 'corepack', 'yarn', 'run', 'test']
}

/* convert build files into one apps.jar that we can use as a dependency in the java part */
tasks.register('createJar', Zip) {
    dependsOn mybuild
    archiveBaseName = 'ui'
    archiveExtension = 'jar'
    destinationDirectory = file("${buildDir}/build/libs")
    from('dist')
    into('public')
}
createJar.dependsOn test

clean.doLast {
    project.delete(files("dist"))
    project.delete(files("build"))
}

/* expose as artifact that can be used as dependency by other modules*/
configurations {
    appResources
}
configurations.default.extendsFrom(configurations.appResources)
artifacts {
    appResources(createJar.getArchiveFile()) {
        builtBy createJar
        type "jar"
    }
}
