---
galaxy_info:
  role_name: httpd_virtualhosts
  author: Sido Haakma
  description: The virtualhost configuration proxypasses the Armadillo service and Minio file storage through virtualhosts.
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
  - name: CentOS
    versions:
    - 7
    - 8

  galaxy_tags: [federation]

dependencies: []